### ISSUE TITLE
Cancel button at open workspace doesn't work

### ISSUE THREAD

**Issue by SilvanVerhoeven** [LivelyKernel/lively.next#23] opened 2020-10-21 12:53 UTC
The cancel button in the window "open window" (Ctrl+K) doesn't close the window.

**Comment by SilvanVerhoeven** [comment] 2020-10-21 12:55
Edit: Only sometimes, not reproduceable...

**Comment by merryman** [comment] 2020-10-21 12:57
Could not reproduce either. Let me know if you catch it again!

**Comment by merryman** [comment] 2021-06-20 13:53
@SilvanVerhoeven is this a thing still? If not I will be closing this.

**Comment by linusha** [comment] 2022-10-19 17:48
Not reproducible anymore.

**Closed by linusha** 2022-10-19 17:48 UTC
Labels: :lady_beetle:  bug
