### ISSUE TITLE
Terminology between "a project" and  "a lively project" respecting our standard is confusing 

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#949] opened 2023-07-18 18:57 UTC
**Describe the bug**
Selected Load from remote repository, and entered the URL of a github repo, in New Project and got a "Loading Project...." which never resolved
Browser console error message was:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'remove')
    at ProjectCreationPromptModel.ProjectCreationPromptModel_resolve_ (prompts.cp.js:197:22)
```
No node.js error logs.
When I checked, the github repo had been cloned

I then went to the dashboard, and got a hang there...
```
landing-page.cp-022f1f0c.js:35079 Uncaught (in promise) Error: Error listing local projects
    at _callee14$ (landing-page.cp-022f1f0c.js:35079:26)
    at tryCatch (deps.js:684:40)
    at Generator.invoke [as _invoke] (deps.js:914:22)
    at Generator.next (deps.js:739:21)
    at asyncGeneratorStep (__rootModule___commonjs-entry-00acb954.js:166:30)
    at _next (__rootModule___commonjs-entry-00acb954.js:188:15)
```

Removing the freshly-created repo (https://github.com/engageLively/fez-intro) fixed the issue, so I suspect it's a missing file Lively requires.

**To Reproduce**
The repo that caused this is: https://github.com/engageLively/fez-intro

**Screenshots**
![image](https://github.com/LivelyKernel/lively.next/assets/656259/c2f2c61f-51a5-4f83-b9a3-5e57eacb095d)

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).

7423f33405ec27b047b0d21c9178fbc55106f885

**Comment by linusha** [comment] 2023-07-18 21:05
First, I think the current state of the system is unfortunately so that the whole system will be crashed once an invalid project is inside of the local_projects folder. I tried fixing this once already, but it seems like it is back. That behavior is of course unacceptable, but I cannot promise when a fix will be there. Once I got it, I will report that in #946.

---

Regarding the cause of this ticket: I have an suspicion what might be happening here, but will really investigate tomorrow, once I am back in the office.
For that, it would be great to get two pieces of information from you:

1. This repository was created from the Create Project Dialogue, right?
2. Could you provide me with a list of repositories with the new lively projects that you already have? The reason is that I might have bricked older Projects with some newer changes I recently made. If that is indeed the problem here, I would prepare PRs for all of your projects to be fixed!

**Comment by linusha** [comment] 2023-07-19 09:47
@rickmcgeer okay, the culprit here is that this repository was not created via the Create Project Dialogue. You can of course also create a project by hand (e.g., in any editor, CLI that you like), but it needs to be adhering to the structure of `lively.project`. This is especially important for the `package.json` file. Using lively itself for this step is thus the easiest way by far.

I understand that the terminology here is suboptimal - we are in a situaton where every normal person will say "I am working on a new project in lively" for anything, but we as maintainers mean something very specific by saying a lively project. Any ideas on how to make this clearer in the dialogue are very much welcome!

**Comment by linusha** [comment] 2024-02-20 14:41
> I understand that the terminology here is sub optimal - we are in a situation where every normal person will say "I am working on a new project in lively" for anything, but we as maintainers mean something very specific by saying a lively project. Any ideas on how to make this clearer in the dialogue are very much welcome!

@merryman thinking about this, I do not think there is a better solution than just being careful that we speak of **lively.projects** when we actually mean a directory conforming to our standard. This should be especially important in the context of documentation/howtows/guides/the website. What do you think? I propose going ahead and closing this.

**Comment by merryman** [comment] 2024-02-21 20:35
I agree, this is basically a wording issue that we need to watch out for when building UIs and writing the documentation in the near future. As long as we do not forget about that this can be closed.

**Closed** 2024-02-22 13:16 UTC
Labels: 💬 ideas welcome, ☭ Halbjahresplan
