### ISSUE TITLE
onBoundsChanged on morph does get called with wrong extent

### ISSUE THREAD

**Issue by T4rikA** [LivelyKernel/lively.next#180] opened 2021-02-15 16:58 UTC
When a morph is resized onBoundsChanged is called. The extent is correct if you enlarge the morph, but if you shrink the morph the extent stays the same as before.

**Comment by merryman** [comment] 2021-02-17 09:14
I tried this on my system and could not reproduce that issue. However instead of "works on my machine", how about the following explaination:
`onBoundsChanged` does not get called with the extent of the morph but with its bounds, which is first of all a Rectangle and not a point (which extent is), and further can be quite different from the extent of the morph if that morph does not clip its submorphs.
So assuming you observed onBoundsChanged getting passed a bounds value with an unchanged extent, I would guess this morph had its `clipMode` set to `"visible"` and had submorphs extending its bounds beyond its actual extent.

**Comment by merryman** [comment] 2021-02-23 10:22
@T4rikA Did this resolve your issue? If so, I would go ahead and close this.

**Closed** 2023-01-18 17:39 UTC
Labels: ❓ needs more spec, 🔍 cause unknown
