### ISSUE TITLE
I'm seeing a lot of persistent popups from the browser, and they don't go away

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#734] opened 2023-03-05 01:22 UTC
You can see it here:
![brower-popups](https://user-images.githubusercontent.com/656259/222936363-73d5d417-eb4f-4ea3-a889-b4fd67ac3f5a.png)

I just did a fresh pull late this week...I'm running 29b508d

**Comment by linusha** [comment] 2023-03-05 15:00
@rickmcgeer is this commit for sure the same as the one in the version checker in the bottom left? I cannot find a commit with that hash in our repository. Could you report back on which version your repository is? Just the last commit message from running `git log` in your `lively.next` repository would also be absolutely fine!

**Comment by linusha** [comment] 2023-03-10 15:16
We cannot reproduce this at all, I'll close this until the problem reoccurs or you supply us with a valid commit hash. :slightly_smiling_face:

**Closed by linusha** 2023-03-10 15:16 UTC
