### ISSUE TITLE
Morphic properties popup has misaligned entry after it was deselected

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#83] opened 2020-11-12 14:24 UTC
I disabled accepts drops, and then when I pulled up the menu again it was misaligned.
![Screen Shot 2020-11-12 at 06 17 07](https://user-images.githubusercontent.com/656259/98951849-97d30d80-24af-11eb-8d3f-116eb90254cc.png)

**Comment by linusha** [comment] 2020-11-12 16:08
@rickmcgeer are you on the latest master? We saw the same behaviour, but 4796062b2c21b1b18b138100e550cfc299c032d2 from yesterday fixed it for us.

**Comment by rickmcgeer** [comment] 2020-11-12 16:17
I'm using a hosted version, and it may not have been updated.  Is there a docker pull I can use to get the latest?

**Comment by merryman** [comment] 2020-11-27 13:59
I guess we can close this now, seems to have been caused by outdated system.

**Closed by merryman** 2020-11-27 13:59 UTC
Labels: bug
