### ISSUE TITLE
Load project from URL hangs

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#866] opened 2023-06-01 00:06 UTC
**Describe the bug**
When I try to load a new project from an URL with an existing repo the screen just hangs...
The project I tried to load was [](https://github.com/engageLively/galyleo-dashboard)

it also appears that the server crashed, with this error:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

```
Error: spawn /bin/bash ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/bash',
  path: '/bin/bash',
  spawnargs: [
    '-c',
    'source /home/rick/lively.next/lively.shell/bin/lively.profile; git remote'
  ]
}


Node.js v19.6.0
```

**To Reproduce**

**Screenshots**

![Screenshot 2023-05-31 165808](https://github.com/LivelyKernel/lively.next/assets/656259/950134d6-9500-4404-b3fd-cb3e08d7e65d)

**Setup**
Please delete non-applicable items!

- Windows

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
a2f54f678bc0e2664d1d9589c4051010fdd87e53

**Comment by linusha** [comment] 2023-06-01 12:55
I just tried that with our windows machine and I cannot reproduce this. I think it would be best if you and @merryman tried to reproduce this as exactly as possible in a screen-share call. I think it's very possible that this is a problem inside of lively, but I cannot possibly know what the cause is at the moment.

Two additional notes:

1. To get the integration really working with engageLively's repositories, you will need to grant some permissions inside of your org. I think you should have gotten an e-mail about this, since @merryman requested those a few hours back. Probably something that you can discuss quickly in the call as well.
2. I am intrigued that you ended up in a state where the Project Creation prompt appeared although you are on `worlds/load?name=__newWorld__` and not on `projectsload?name=__newProject__`. Did you run `make artifacts` after pulling? If not, please do so, the changes we made require a rebuild of the loading screen and the landing page!

**Comment by merryman** [comment] 2023-06-01 15:19
@linusha I looked into the issue with @rickmcgeer and it was due to a missing rebuild of the artifacts. Maybe we should consider automatising this step again (reintroduce an `update.sh`). If there are no further objections I will close this for now.

**Closed** 2023-06-01 15:34 UTC
Labels: :lady_beetle:  bug
