### ISSUE TITLE
Labels aren't dropped on the scene graph when labels are selected in the shapes menu

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#242] opened 2021-04-07 00:52 UTC
This is probably related to the menu issue, because when I drag the top bar out of the way they appear in the top-left corner
![image](https://user-images.githubusercontent.com/656259/113794934-8dd0d600-9700-11eb-957f-22a91785031d.png)

**Comment by merryman** [comment] 2021-04-07 14:39
Duplicate of #241

**Closed** 2021-04-08 14:10 UTC
Labels: duplicate
