### ISSUE TITLE
Worlds don't serialize due to missing Classes

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#155] opened 2021-01-08 14:09 UTC

**Comment by rickmcgeer** [comment] 2021-01-08 14:11
Here's the error message:
Error saving world: Error: Error snapshotting morph: Cannot recreate morph from snapshot!
TypeError: Illegal constructor
    at ClassHelper.restoreIfClassInstance (/lively.serializer2/class-helper.js:152)
    at ClassPlugin.deserializeObject (/lively.serializer2/plugins.js:99)
    at ObjectPool.plugin_deserializeObject (/lively.serializer2/object-pool.js:337)
    at ObjectRef.recreateObjFromSnapshot (/lively.serializer2/object-pool.js:559)
    at Function.fromSnapshot (/lively.serializer2/object-pool.js:636)
    at ObjectPool.readSnapshot (/lively.serializer2/object-pool.js:236)
    at ObjectPool.resolveFromSnapshotAndId (/lively.serializer2/object-pool.js:252)
    at Window.deserialize (/lively.serializer2/index.js:55)
    at step2 (/lively.serializer2/index.js:67)
    at async Window.createMorphSnapshot (/lively.morphic/serialization.js:179)
I can't tell from this which object is causing the problem.  It could be Dashboard or googleChartMorph.  googleChartMorph is incredibly skinny; as for dashboard, it does get a per-chart link to the chart morph...

**Comment by rickmcgeer** [comment] 2021-01-08 14:12
Incidentally, once I understand the problem it should be easy to work around, so this may be yet another programmer-education thing.

**Comment by merryman** [comment] 2021-01-08 14:57
Yes, this situation is unacceptable. I will push forward to make the serialization process less conservative and return a more comprehensive list of "These Object failed to serialize due to the following errors" report. After that the user is free to proceed and save the snapshot or cancel the save.

**Comment by rickmcgeer** [comment] 2021-01-08 22:43
Our session this morning led to an easy workaround, which I just implemented -- and thanks for all of your help.  I do agree we need to trace down the underlying issue in Lively.

**Comment by merryman** [comment] 2021-05-31 15:40
duplicate of #258

**Closed by merryman** 2021-05-31 15:40 UTC
Labels: enhancement, 🪲 bug
