### ISSUE TITLE
Unify linebreaks between platforms on text enter/render/save

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#187] opened 2021-02-20 02:12 UTC
When I use the Object Editor (or workspace) and select part of a line, the whole line shows as selected.  However, when I copy/cut, I only copy/cut the right amount.  That is good, but it would be better if the highlight showed this.
![image](https://user-images.githubusercontent.com/656259/108579918-0eb54900-72de-11eb-8943-d1ad739d386f.png)

**Comment by merryman** [comment] 2021-02-23 09:52
This is a bug in the text bounds computation. Since I can't reproduce this its hard to fix. We first need to figure out the exact steps to end up in this situation, then we can start fixing.

**Comment by merryman** [comment] 2021-03-11 19:05
We recently discovered this may be due to \r\n line breaks inserted by other code editors on windows. In case you have edited or pasted code from a windows machine with a custom Editor such as Notepad, this may have inserted those kinds of line breaks which right now mess up the text layout of the text morphs.

I proper fix would be to check for these characters and remove them before rendering text. Maybe inside the internal document creation would be the proper way to filter those symbols out.

**Comment by merryman** [comment] 2021-06-20 14:01
Will be addressed by #213

**Comment by merryman** [comment] 2023-07-07 13:57
@linusha Recently mentioned that there is a git internal feature that does *exactly* what we need to solve this.

**Comment by linusha** [comment] 2023-07-07 15:42
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Closed** 2023-07-17 15:04 UTC
Labels: :lady_beetle:  bug
