### ISSUE TITLE
lively crashing under docker on macOS

### ISSUE THREAD

**Issue by lin564** [LivelyKernel/lively.next#846] opened 2023-05-19 15:43 UTC
**Describe the bug**
The container exits when localhost 127.0.0.1:9011/dashboard is accessed. The original URL was 127.0.0.1:9011 
Error message from the container log is 
2023-05-19 11:26:36 Setting env vars for FLATN_PACKAGE_DIRS, FLATN_PACKAGE_COLLECTION_DIRS, FLATN_DEV_PACKAGE_DIRS for lively.next
2023-05-19 11:26:40 2023-05-19T15:26:40.248Z info: [lively.server] system base directory: /Users/lindabernard/projects/lively.next
2023-05-19 11:26:40 2023-05-19T15:26:40.251Z info: [lively.modules] SystemJS configured with lively.transpiler & babel
2023-05-19 11:26:41 2023-05-19T15:26:41.919Z info: [lively.server] 1. preparing system
2023-05-19 11:26:50 2023-05-19T15:26:50.993Z info: [lively.server] 2. loading /Users/lindabernard/projects/lively.next/config.js
2023-05-19 11:26:51 2023-05-19T15:26:51.003Z info: [lively.server] 3. starting server
2023-05-19 11:26:52 2023-05-19T15:26:52.905Z info: [Test Runner] Started
2023-05-19 11:26:52 2023-05-19T15:26:52.914Z info: [lively.server] 4. server sucessfully started
2023-05-19 11:26:52 2023-05-19T15:26:52.925Z info: [l2l] L2LTracker(l2l, open: true) client connected S1VTaTLhE5p7Sbx0AAAB 127.0.0.1
2023-05-19 11:26:52 2023-05-19T15:26:52.927Z info: Reconnected at 15:26:52 GMT+0000 (Coordinated Universal Time)
2023-05-19 11:26:52 2023-05-19T15:26:52.930Z info: headless-broker ready
2023-05-19 11:33:03 node:internal/process/promises:288
2023-05-19 11:33:03             triggerUncaughtException(err, true /* fromPromise */);
2023-05-19 11:33:03             ^
2023-05-19 11:33:03 
2023-05-19 11:33:03 [Error: ENOENT: no such file or directory, open '/Users/lindabernard/projects/lively.next/lively.freezer/landing-page/index.html'] {
2023-05-19 11:33:03   errno: -2,
2023-05-19 11:33:03   code: 'ENOENT',
2023-05-19 11:33:03   syscall: 'open',
2023-05-19 11:33:03   path: '/Users/lindabernard/projects/lively.next/lively.freezer/landing-page/index.html'
2023-05-19 11:33:03 }
2023-05-19 11:33:03 
2023-05-19 11:33:03 Node.js v18.16.0
2023-05-19 11:34:37 Setting env vars for FLATN_PACKAGE_DIRS, FLATN_PACKAGE_COLLECTION_DIRS, FLATN_DEV_PACKAGE_DIRS for lively.next
2023-05-19 11:34:40 2023-05-19T15:34:40.617Z info: [lively.server] system base directory: /Users/lindabernard/projects/lively.next
2023-05-19 11:34:40 2023-05-19T15:34:40.625Z info: [lively.modules] SystemJS configured with lively.transpiler & babel
2023-05-19 11:34:42 2023-05-19T15:34:42.283Z info: [lively.server] 1. preparing system
2023-05-19 11:34:50 2023-05-19T15:34:50.885Z info: [lively.server] 2. loading /Users/lindabernard/projects/lively.next/config.js
2023-05-19 11:34:50 2023-05-19T15:34:50.904Z info: [lively.server] 3. starting server
2023-05-19 11:34:52 2023-05-19T15:34:52.607Z info: [Test Runner] Started
2023-05-19 11:34:52 2023-05-19T15:34:52.619Z info: [lively.server] 4. server sucessfully started
2023-05-19 11:34:52 2023-05-19T15:34:52.622Z info: [l2l] L2LTracker(l2l, open: true) client connected OnDohlUEccwwcIZYAAAB 127.0.0.1
2023-05-19 11:34:52 2023-05-19T15:34:52.624Z info: Reconnected at 15:34:52 GMT+0000 (Coordinated Universal Time)
2023-05-19 11:34:52 2023-05-19T15:34:52.630Z info: headless-broker ready
2023-05-19 11:35:03 node:internal/process/promises:288
2023-05-19 11:35:03             triggerUncaughtException(err, true /* fromPromise */);
2023-05-19 11:35:03             ^
2023-05-19 11:35:03 
2023-05-19 11:35:03 [Error: ENOENT: no such file or directory, open '/Users/lindabernard/projects/lively.next/lively.freezer/landing-page/index.html'] {
2023-05-19 11:35:03   errno: -2,
2023-05-19 11:35:03   code: 'ENOENT',
2023-05-19 11:35:03   syscall: 'open',
2023-05-19 11:35:03   path: '/Users/lindabernard/projects/lively.next/lively.freezer/landing-page/index.html'
2023-05-19 11:35:03 }
2023-05-19 11:35:03 
2023-05-19 11:35:03 Node.js v18.16.0

**To Reproduce**
Clone lively - the build I cloned was current version as of May 19, 2023. 
make docker-build
restarted container a couple of times and same thing happened.

**Screenshots**

**Setup**
Please delete non-applicable items!

- macOS
- Docker

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).

**Comment by merryman** [comment] 2023-05-19 16:38
@linusha It appears we no longer build the landing page by default. This is why when @lin564 attempts to just open `localhost:9011/` it fails loading the landing page. Has something changed in that area recently? Something with the CI flag?

**Comment by linusha** [comment] 2023-05-19 17:33
Hi, thanks for the report! I think I solved the cause for your issue. After we merged #848 you should be able to pull and try again! Sorry for the inconvenience.

**Comment by rickmcgeer** [comment] 2023-05-19 18:47
Thanks, @linusha .  Just to give some context on the cause of this, @lin564 is a colleague of mine and @merryman.  She is primarily a designer but does some coding as well.  She works with me on a number of projects, where she'll do the design and I'll help out by doing a little coding.
In this case, @lin564 was very impressed with the embedding inherent in Lively and the fact that we're able to get things done very quickly, and she wanted to install Lively on her laptop to play with it.  However, she is using node v19, and doesn't want to downgrade native because she uses other browser-based environments, so we tried Docker as a workaround.
@lin564 is very much a user that we'd like to understand well, because the issues she runs into will be issues our typical user will have.
In my view, the best solution for this is a Cloud-based environment, which will free @lin564 and similar users from these software engineering/IT tasks.

**Closed** 2023-05-19 19:32 UTC
Labels: :lady_beetle:  bug, docker 🐳
