### ISSUE TITLE
Episodic load bug

### ISSUE THREAD

**Issue by rickmcgeer** [LivelyKernel/lively.next#1676] opened 2024-09-05 19:58 UTC
**Describe the bug**
Every so often, the Galyleo Dashboard project hangs on loading, and I see this error:
```
landing-page.cp-f59ae217.js:10768 Uncaught (in promise) TypeError: deployKeys.find is not a function
    at _callee7$ (landing-page.cp-f59ae217.js:10768:50)
    at tryCatch (deps.js:722:40)
    at Generator.invoke [as _invoke] (deps.js:950:22)
    at Generator.next (deps.js:777:21)
    at asyncGeneratorStep (__rootModule___commonjs-entry-35de395a.js:48:30)
    at _next (__rootModule___commonjs-entry-35de395a.js:70:15)
```
It seems to happen when the loading tab is hidden, so it may have to do with something being swapped out.  When it does successfully load, I see this:
```
landing-page.cp-f59ae217.js:10546 
        
        
       POST https://api.github.com/repos/LivelyKernel/partsbin/keys 404 (Not Found)
```
which may be unrelated

**Setup**
Please delete non-applicable items!

- Windows
- Linux

**Version**: Please paste the lively.next commit on which the problem occurred here (use the copy button of the Version Checker in the bottom left corner).
9c51c586cfca90d3df3c4439a9677adfa40476de

**Comment by merryman** [comment] 2024-09-06 07:59
I think this is a duplicate of #1674. Did you try the suggestion from @linusha?

**Comment by linusha** [comment] 2024-10-28 21:19
Let's close this as a duplicate.

**Closed by linusha** 2024-10-28 21:19 UTC
Labels: :lady_beetle:  bug, 🖨️ duplicate
